### ISSUE TITLE
Parsing ENV not working for int/float/bool

### ISSUE THREAD

**Issue by staaam** [zifeo/dataconf#35]
Looks like ENV loading doesn't support int/float/bool , since this requires additional parsing.

Below example will raise exception, while would be expected to parse correctly.

```python
from typing import Optional
import os
from dataclasses import dataclass
import dataconf


@dataclass
class Example:
    hello: Optional[str]
    world: str
    float_num: float
    int_num: int
    bool_var: bool


os.environ["DC_WORLD"] = "monde"
os.environ["DC_FLOAT_NUM"] = "1.3"
os.environ["DC_INT_NUM"] = "2"
os.environ["DC_BOOL_VAR"] = "true"

print(dataconf.env("DC", Example))
```

Actual:
```
Traceback (most recent call last):
  File "/Users/any/playground/dataconf_check.py", line 21, in <module>
    print(dataconf.env("DC", Example))
  File "/Users/any/.venv/lib/python3.9/site-packages/dataconf/main.py", line 59, in env
    return multi.env(prefix).on(clazz)
  File "/Users/any/.venv/lib/python3.9/site-packages/dataconf/main.py", line 52, in on
    return parse(conf, clazz)
  File "/Users/any/.venv/lib/python3.9/site-packages/dataconf/main.py", line 14, in parse
    return utils.__parse(conf, clazz, "")
  File "/Users/any/.venv/lib/python3.9/site-packages/dataconf/utils.py", line 68, in __parse
    fs[f.name] = __parse(val, f.type, f"{path}.{f.name}")
  File "/Users/any/.venv/lib/python3.9/site-packages/dataconf/utils.py", line 134, in __parse
    return __parse_type(
  File "/Users/any/.venv/lib/python3.9/site-packages/dataconf/utils.py", line 34, in __parse_type
    raise TypeConfigException(f"expected type {clazz} at {path}, got {type(value)}")
dataconf.exceptions.TypeConfigException: expected type <class 'float'> at .float_num, got <class 'str'>
```

Expected:
```
Example(hello=None, world='monde', float_num=1.3, int_num=2, bool_var=True)
```

**Comment by zifeo** [comment]
@staaam I opened a fix in #36 but I am not yet happy of the solution. You can try the fix through `poetry add git+https://github.com/zifeo/dataconf.git#strict`, open for reviews/comments.
